# Generated by Django 4.0.2 on 2022-02-13 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Место занятий')),
            ],
            options={
                'verbose_name': 'Место занятий',
                'verbose_name_plural': 'Места занятий',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('content', models.TextField(blank=True, verbose_name='Содержание')),
                ('rate', models.IntegerField(verbose_name='Рейтинг')),
                ('year', models.IntegerField(verbose_name='Стаж')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.place', verbose_name='Место занятий (id)')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.subject', verbose_name='Предмет (id)')),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителя',
            },
        ),
    ]
