# Generated by Django 4.0.2 on 2022-02-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='salary',
            field=models.IntegerField(default='1', verbose_name='Ставка'),
            preserve_default=False,
        ),
    ]
