# Generated by Django 4.0.2 on 2022-02-13 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_teacher_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='content',
        ),
    ]
